---
- name: install nginx
  hosts: webservers
  become: yes
  roles:
    - role: nginx-role

- name: install and configure haproxy
  hosts: loadbalancers
  become: yes
  roles:
    - role: haproxy-role

- name: install and configure MASTER keepalived
  hosts: loadbalancers
  become: yes
  roles:
    - role: keepalived-role
